management:
  health:
    circuitbreakers:
      enabled : true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts : 3
        waitDuration : 10s
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 5s
        limitForPeriod: 1
        timeoutDuration: 1s
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator : true
        slidingWindowSize : 7
        minimumNumberOfCalls: 10
        failureRateThreshold : 50
        waitDurationOpenState : 20s
        permittedNumberOfCallsInHalfOpenState : 3
        eventConsumerBufferSize : 10
      shippingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize : 5
        minimumNumberOfCalls: 2
        failureRateThreshold : 50
        waitDurationOpenState : 20s
        permittedNumberOfCallsInHalfOpenState : 3
        eventConsumerBufferSize : 10
